/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/67a47721736ce9f3e126d847.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei"; // Drei hooks for GLTF models and animations
import { useFrame } from "@react-three/fiber"; // React Three Fiber hook for frame updates
import { button, useControls } from "leva"; // Leva hooks for GUI controls
import React, { useEffect, useRef, useState, useMemo } from "react"; // React hooks

import * as THREE from "three"; // Three.js library
import { useChat } from "../hooks/useChat"; // Custom hook for chat functionality

// Define facial expressions with morph target values
const facialExpressions = {
  default: {}, // Default neutral expression
  smile: { // Smiling expression
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: { // Funny/crazy expression
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: { // Sad expression
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: { // Surprised expression
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: { // Angry expression
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: { // Crazy expression
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

// Mapping of phonemes to viseme morph targets for lip sync
const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false; // Global flag for setup mode (disables automatic animations)

// Store bone references for gesture animation
let gestureBones = {};

// Main Avatar component that renders and animates the 3D teacher model
export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF("/models/67a47721736ce9f3e126d847.glb"); // Load main avatar model
  const { message, onMessagePlayed } = useChat(); // Get current message and callback from chat context

  const group = useRef(); // Ref for the avatar group
  const { animations } = useGLTF("/models/animations.glb"); // Load animation clips
  const { actions } = useAnimations(animations, group); // Get animation actions

  const [animation, setAnimation] = useState("Idle"); // State for primary animation
  const [secondaryAnimation, setSecondaryAnimation] = useState(null); // State for secondary animation
  const [lipsync, setLipsync] = useState(); // State for lip sync data
  const [currentMessage, setCurrentMessage] = useState(null); // State for current message being processed
  const [audio, setAudio] = useState(null); // State for audio element
  const [facialExpression, setFacialExpression] = useState(""); // State for facial expression
  const [gestureData, setGestureData] = useState({ compressed: { bones: [], frames: [] } }); // State for gesture data
  
  // Animation timing
  const lastUpdateRef = useRef(0); // Ref to track last update time for gesture animation
  const currentFrameRef = useRef(0); // Ref to track current frame for gesture animation

  // Log all bone names for debugging
  useEffect(() => {
    console.log("Available bones in GLB model:"); // Log header
    scene.traverse((child) => { // Traverse all children in the scene
      if (child.isBone) { // Check if child is a bone
        console.log("- Bone:", child.name); // Log bone name
        gestureBones[child.name] = child; // Store bone reference
      }
    });
  }, [scene]); // Run effect when scene changes

  // List of available talking animations
  const talkingAnimations = ["Talking_0", "Talking_1", "Talking_2", "Talking_1", "Talking_4", "Talking_5", "Talking_6", "Talking_7"];
  const availableAnimations = animations.map((a) => a.name); // Map animation names

  // Effect to update current message when chat message changes
  useEffect(() => {
    if (message) { // Check if there's a message
      setCurrentMessage(message); // Set current message
      if (message.gesture) { // Check if message has gesture data
        setGestureData(message.gesture); // Set gesture data
        console.log("Gesture data received:", message.gesture); // Log gesture data
        currentFrameRef.current = 0; // Reset gesture frame counter
      }
    }
  }, [message]); // Run effect when message changes

  // Effect to handle message playback (audio and animations)
  useEffect(() => {
    if (!currentMessage || !currentMessage.audio) return; // Return if no message or audio

    // Select animation based on message data or use random talking animation
    let selectedAnim = "Idle"; // Default animation
    if (currentMessage.animation && availableAnimations.includes(currentMessage.animation)) { // Check if specific animation is available
      selectedAnim = currentMessage.animation; // Use specific animation
    } else if ((currentMessage.animation || currentMessage.text) && talkingAnimations.length > 0) { // Check if there's text but no specific animation
      // If there's text but no specific animation, randomly select a talking animation
      const randomIndex = Math.floor(Math.random() * talkingAnimations.length); // Generate random index
      selectedAnim = talkingAnimations[randomIndex]; // Select random talking animation
    }
    setAnimation(selectedAnim); // Set primary animation
    
    // Set secondary animation if provided
    setSecondaryAnimation(currentMessage.secondaryAnimation || null);
    
    console.log(`📥 Received animation data: Primary=${currentMessage.animation}, Secondary=${currentMessage.secondaryAnimation}`); // Log received animation data
    console.log(`🔄 Setting animations: Primary=${selectedAnim}, Secondary=${currentMessage.secondaryAnimation || null}`); // Log setting animations

    setFacialExpression(currentMessage.facialExpression || "smile"); // Set facial expression
    setLipsync(currentMessage.lipsync || { mouthCues: [] }); // Set lip sync data

    // Handle both base64 string and file path for audio
    const audioSrc = currentMessage.audio.startsWith('data:') ? 
      currentMessage.audio : // Use base64 data directly
      "data:audio/mp3;base64," + currentMessage.audio; // Prepend base64 header
    const audio = new Audio(audioSrc); // Create new audio element
    audio.addEventListener('canplay', () => { // Add event listener for when audio can play
      // Audio is ready to play
      audio.play().catch(e => console.error("Audio play error:", e)); // Play audio and catch errors
    });
    setAudio(audio); // Set audio state

    // Add event listener for when audio ends
    audio.addEventListener('ended', () => {
      setAnimation("Idle"); // Reset to idle animation
      setSecondaryAnimation(null); // Clear secondary animation
      setFacialExpression("neutral"); // Reset facial expression
      onMessagePlayed(); // Call callback when message is finished
    });
  
    // Clean up audio on unmount
    return () => {
      if (audio) { // Check if audio exists
        audio.pause(); // Pause audio
        audio.removeAttribute('src'); // Remove source attribute
        audio.load(); // Reset audio
      }
    };
  }, [currentMessage]); // Run effect when currentMessage changes

  // Effect to handle animation playback
  useEffect(() => {
    // Handle primary animation
    if (animation && actions[animation]) { // Check if animation exists
      console.log("🎬 Playing primary animation:", animation); // Log playing animation
      actions[animation].reset().fadeIn(0.2).play(); // Reset, fade in, and play animation
    } else if (animation) { // Check if animation is set but not found
      console.warn("⚠️ Primary animation not found:", animation); // Log warning
    }
    
    // Handle secondary animation
    if (secondaryAnimation && actions[secondaryAnimation]) { // Check if secondary animation exists
      console.log("🎬 Playing secondary animation:", secondaryAnimation); // Log playing animation
      actions[secondaryAnimation].reset().fadeIn(0.2).play(); // Reset, fade in, and play animation
    } else if (secondaryAnimation) { // Check if secondary animation is set but not found
      console.warn("⚠️ Secondary animation not found:", secondaryAnimation); // Log warning
    }
    
    // Log current animation states
    console.log(`🔄 Current animation states: Primary=${animation}, Secondary=${secondaryAnimation}`);
    
    // Cleanup function to fade out animations
    return () => {
      if (animation && actions[animation]) { // Check if primary animation exists
        console.log("🛑 Stopping primary animation:", animation); // Log stopping animation
        actions[animation]?.fadeOut(0.2); // Fade out animation
      }
      if (secondaryAnimation && actions[secondaryAnimation]) { // Check if secondary animation exists
        console.log("🛑 Stopping secondary animation:", secondaryAnimation); // Log stopping animation
        actions[secondaryAnimation]?.fadeOut(0.2); // Fade out animation
      }
    };
  }, [animation, secondaryAnimation, actions]); // Run effect when animations change

  // Function to smoothly transition morph target values
  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => { // Traverse all children in the scene
      if (child.isSkinnedMesh && child.morphTargetDictionary) { // Check if child is a skinned mesh with morph targets
        const index = child.morphTargetDictionary[target]; // Get morph target index
        if (index === undefined || child.morphTargetInfluences[index] === undefined) { // Check if target exists
          return; // Return if target doesn't exist
        }
        // Linear interpolation to smoothly transition to target value
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index], // Current value
          value, // Target value
          speed // Interpolation speed
        );

        if (!setupMode) { // Check if not in setup mode
          try {
            set({ // Update Leva control
              [target]: value, // Set target value
            });
          } catch (e) {} // Ignore errors
        }
      }
    });
  };

  const [blink, setBlink] = useState(false); // State for eye blinking
  const [winkLeft, setWinkLeft] = useState(false); // State for left eye wink
  const [winkRight, setWinkRight] = useState(false); // State for right eye wink

  // Frame update function for real-time animations
  useFrame((state, delta) => {
    // Handle gesture animations
    if (gestureData && gestureData.compressed && gestureData.compressed.frames.length > 0) { // Check if gesture data exists
      const { bones, frames } = gestureData.compressed; // Extract bones and frames
      
      // Update timing
      const now = performance.now() / 1000; // Get current time in seconds
      if (lastUpdateRef.current === 0) { // Check if this is the first update
        lastUpdateRef.current = now; // Set initial update time
      }
      
      const elapsedTime = now - lastUpdateRef.current; // Calculate elapsed time
      lastUpdateRef.current = now; // Update last update time
      
      // Find current and next frames for interpolation
      let currentFrame = frames[currentFrameRef.current]; // Get current frame
      let nextFrame = frames[Math.min(currentFrameRef.current + 1, frames.length - 1)]; // Get next frame
      
      // Advance frame based on elapsed time (assuming 30 FPS source)
      const frameDuration = 1 / 30; // Duration of each frame
      if (elapsedTime >= frameDuration) { // Check if enough time has passed
        currentFrameRef.current = Math.min(currentFrameRef.current + 1, frames.length - 1); // Advance frame counter
        currentFrame = frames[currentFrameRef.current]; // Get new current frame
        nextFrame = frames[Math.min(currentFrameRef.current + 1, frames.length - 1)]; // Get new next frame
      }
      
      // Apply bone rotations
      if (currentFrame && currentFrame.rot) { // Check if current frame has rotation data
        const t = Math.min(1, (elapsedTime % frameDuration) / frameDuration); // Calculate interpolation factor
        
        for (let i = 0; i < bones.length; i++) { // Iterate through bones
          const boneName = bones[i]; // Get bone name
          const bone = gestureBones[boneName]; // Get bone reference
          
          if (bone && currentFrame.rot[i]) { // Check if bone and rotation data exist
            // Get current and next quaternions
            const currentQuat = new THREE.Quaternion( // Create quaternion from current frame
              currentFrame.rot[i][0], // X component
              currentFrame.rot[i][1], // Y component
              currentFrame.rot[i][2], // Z component
              currentFrame.rot[i][3] // W component
            );
            
            let finalQuat = currentQuat; // Initialize final quaternion
            
            // If we have a next frame, interpolate between them
            if (nextFrame && nextFrame.rot && nextFrame.rot[i]) { // Check if next frame has rotation data
              const nextQuat = new THREE.Quaternion( // Create quaternion from next frame
                nextFrame.rot[i][0], // X component
                nextFrame.rot[i][1], // Y component
                nextFrame.rot[i][2], // Z component
                nextFrame.rot[i][3] // W component
              );
              
              // Spherical linear interpolation for smooth rotation transitions
              finalQuat = currentQuat.clone().slerp(nextQuat, t); // Interpolate between quaternions
            }
            
            // Apply rotation to bone
            bone.quaternion.copy(finalQuat); // Copy final quaternion to bone
          }
        }
      }
    }
    
    // Handle facial expressions and lipsync
    !setupMode && // Only run if not in setup mode
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => { // Iterate through morph targets
        const mapping = facialExpressions[facialExpression]; // Get facial expression mapping
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") { // Skip eye blink targets (handled separately)
          return; // Continue to next iteration
        }
        if (mapping && mapping[key]) { // Check if expression has value for this target
          lerpMorphTarget(key, mapping[key], 0.1); // Apply expression value
        } else {
          lerpMorphTarget(key, 0, 0.1); // Reset to neutral
        }
      });

    // Handle eye blinking and winking
    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5); // Left eye blink/wink
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5); // Right eye blink/wink

    // LIPSYNC
    if (setupMode) { // Check if in setup mode
      return; // Skip lip sync in setup mode
    }
    const appliedMorphTargets = []; // Array to track applied morph targets
    // Check if all required objects exist and audio is ready
    if (currentMessage && lipsync && audio && audio.readyState >= 2) { // Check if all required data exists
      // Check if lipsync and lipsync.mouthCues exist and are arrays
      const mouthCues = lipsync.mouthCues || []; // Get mouth cues or empty array
      if (Array.isArray(mouthCues)) { // Check if mouth cues is an array
        const currentAudioTime = audio.currentTime || 0; // Get current audio time
        for (let i = 0; i < mouthCues.length; i++) { // Iterate through mouth cues
          const mouthCue = mouthCues[i]; // Get current mouth cue
          if (mouthCue && 
              typeof mouthCue.start === 'number' && 
              typeof mouthCue.end === 'number' &&
              currentAudioTime >= mouthCue.start && // Check if current time is within cue
              currentAudioTime <= mouthCue.end) {
            if (corresponding[mouthCue.value]) { // Check if phoneme has corresponding viseme
              appliedMorphTargets.push(corresponding[mouthCue.value]); // Add to applied targets
              lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2); // Apply viseme
            }
            break; // Exit loop after finding matching cue
          }
        }
      }
    }

    // Reset morph targets that weren't applied
    Object.values(corresponding).forEach((value) => { // Iterate through all visemes
      if (appliedMorphTargets.includes(value)) { // Check if viseme was applied
        return; // Skip if applied
      }
      lerpMorphTarget(value, 0, 0.1); // Reset to neutral
    });
  });

  // Leva GUI controls for facial expressions
  useControls("FacialExpressions", {
    chat: button(() => chat()), // Button to trigger chat
    winkLeft: button(() => { // Button to trigger left wink
      setWinkLeft(true); // Set left wink state
      setTimeout(() => setWinkLeft(false), 300); // Reset after 300ms
    }),
    winkRight: button(() => { // Button to trigger right wink
      setWinkRight(true); // Set right wink state
      setTimeout(() => setWinkRight(false), 300); // Reset after 300ms
    }),
    animation: { // Dropdown for animation selection
      value: animation, // Current animation value
      options: animations.map((a) => a.name), // Available animation options
      onChange: (value) => setAnimation(value), // Update animation on change
    },
    facialExpression: { // Dropdown for facial expression selection
      options: Object.keys(facialExpressions), // Available expression options
      onChange: (value) => setFacialExpression(value), // Update expression on change
    },
    enableSetupMode: button(() => { // Button to enable setup mode
      setupMode = true; // Set setup mode flag
    }),
    disableSetupMode: button(() => { // Button to disable setup mode
      setupMode = false; // Clear setup mode flag
    }),
    logMorphTargetValues: button(() => { // Button to log current morph target values
      const emotionValues = {}; // Object to store emotion values
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => { // Iterate through morph targets
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") { // Skip eye blink targets
          return; // Continue to next iteration
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[ // Get current morph target influence
            nodes.EyeLeft.morphTargetDictionary[key] // Get target index
          ];
        if (value > 0.01) { // Check if value is significant
          emotionValues[key] = value; // Add to emotion values
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2)); // Log emotion values
    }),
  });

  // Leva GUI controls for morph targets
  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => { // Map morph targets to controls
        return {
          [key]: { // Create control for each morph target
            label: key, // Label for control
            value: 0, // Initial value
            min: nodes.EyeLeft.morphTargetInfluences[ // Minimum value
              nodes.EyeLeft.morphTargetDictionary[key] // Get target index
            ],
            max: 1, // Maximum value
            onChange: (val) => { // Update function
              if (setupMode) { // Check if in setup mode
                lerpMorphTarget(key, val, 1); // Apply morph target value directly
              }
            },
          },
        };
      })
    )
  );

  // Effect for automatic eye blinking
  useEffect(() => {
    let blinkTimeout; // Variable to store timeout ID
    const nextBlink = () => { // Function to schedule next blink
      blinkTimeout = setTimeout(() => { // Set timeout for next blink
        setBlink(true); // Trigger blink
        setTimeout(() => { // Set timeout to end blink
          setBlink(false); // End blink
          nextBlink(); // Schedule next blink
        }, 200); // Blink duration: 200ms
      }, THREE.MathUtils.randInt(1000, 5000)); // Random interval: 1-5 seconds
    };
    nextBlink(); // Start blinking
    return () => clearTimeout(blinkTimeout); // Clear timeout on unmount
  }, []); // Run effect once on mount

  // Main render function for the avatar
  return (
    <group {...props} dispose={null} ref={group}> {/* Avatar group container */}
      <primitive object={nodes.Hips} /> {/* Hips bone as primitive */}
      {/* Render all skinned meshes with their morph targets */}
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Headwear.geometry}
        material={materials.Wolf3D_Headwear}
        skeleton={nodes.Wolf3D_Headwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
    </group>
  );
}

// Preload GLTF models for better performance
useGLTF.preload("/models/67a47721736ce9f3e126d847.glb");
useGLTF.preload("/models/untitled.glb");