/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei"; // Drei hooks for GLTF models and animations
import { useFrame } from "@react-three/fiber"; // React Three Fiber hook for frame updates
import { button, useControls } from "leva"; // Leva hooks for GUI controls
import React, { useEffect, useRef, useState } from "react"; // React hooks
import { Text } from "@react-three/drei"; // Drei component for 3D text

import * as THREE from "three"; // Three.js library
import { useChat } from "../hooks/useChat"; // Custom hook for chat functionality

// Define facial expressions with morph target values
const facialExpressions = {
  default: {}, // Default neutral expression
  smile: { // Smiling expression
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: { // Funny/crazy expression
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: { // Sad expression
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: { // Surprised expression
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: { // Angry expression
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: { // Crazy expression
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

// Mapping of phonemes to viseme morph targets for lip sync
const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false; // Global flag for setup mode (disables automatic animations)

// AvatarStudent component that renders and animates the 3D student model
export function AvatarStudent(props) {
  const { nodes, materials, scene } = useGLTF("/models/64f1a714fe61576b46f27ca2.glb"); // Load student avatar model
  const { message, onMessagePlayed, chat } = useChat(); // Get chat functions and state from context

  const [lipsync, setLipsync] = useState(); // State for lip sync data

  const { animations } = useGLTF("/models/animations.glb"); // Load animation clips
  const group = useRef(); // Ref for the avatar group
  const { actions, mixer } = useAnimations(animations, group); // Get animation actions and mixer
  const [animation, setAnimation] = useState(""); // State for current animation
  const [currentMessage, setCurrentMessage] = useState(null); // State for current message being processed
  const [audio, setAudio] = useState(null); // State for audio element
  const [facialExpression, setFacialExpression] = useState(""); // State for facial expression
  const [userInput, setUserInput] = useState(""); // State for user input text
  const [isListening, setIsListening] = useState(false); // State for listening indicator

  // Set the initial animation based on available animations
  useEffect(() => {
    if (animations && animations.length > 0) { // Check if animations are loaded
      console.log("Available animations:", animations.map(a => a.name)); // Log available animations
      // Look for sitting animations first, then fall back to any idle animation, then to the first available
      const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name; // Find sitting animation
      const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name; // Find idle animation
      const firstAnimation = animations[0].name; // Get first animation
      
      const initialAnimation = sittingAnimation || idleAnimation || firstAnimation; // Select appropriate initial animation
      setAnimation(initialAnimation); // Set initial animation
      console.log("Setting initial animation to:", initialAnimation); // Log initial animation
    }
  }, [animations]); // Run effect when animations change

  // Handle user input to show listening expression
  useEffect(() => {
    if (message && message.text) { // Check if there's a message with text
      // Set listening state and facial expression when user sends input
      setIsListening(true); // Show listening indicator
      setFacialExpression("smile"); // Set smiling expression
      setUserInput(message.text); // Store user input text
      
      // Reset to default expression after a delay
      const timer = setTimeout(() => { // Set timeout to reset
        setIsListening(false); // Hide listening indicator
        setFacialExpression("default"); // Reset to default expression
        setUserInput(""); // Clear user input
      }, 3000); // Reset after 3 seconds
      
      return () => clearTimeout(timer); // Clear timeout on unmount
    }
  }, [message]); // Run effect when message changes

  // Play animations
  useEffect(() => {
    // Always ensure we have a valid animation
    const currentAnimation = (animation && animation !== "") ? animation : "Idle"; // Use current or default to Idle
    console.log("Trying to play animation:", currentAnimation); // Log animation attempt
    
    // Check if animation exists
    if (!actions[currentAnimation] || !animations) { // Check if animation or actions don't exist
      console.log("Animation not found or no animations loaded"); // Log missing animation
      // Try to find an appropriate fallback animation
      if (animations && animations.length > 0) { // Check if animations exist
        // Look for sitting animations first, then fall back to any idle animation, then to the first available
        const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name; // Find sitting animation
        const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name; // Find idle animation
        const firstAnimation = animations[0].name; // Get first animation
        
        const fallbackAnimation = sittingAnimation || idleAnimation || firstAnimation; // Select fallback animation
        
        if (fallbackAnimation && actions[fallbackAnimation]) { // Check if fallback animation exists
          console.log("Falling back to animation:", fallbackAnimation); // Log fallback animation
          setAnimation(fallbackAnimation); // Set fallback animation
          return; // Exit effect
        }
      }
      return; // Exit effect
    }

    console.log("🎬 Playing animation:", currentAnimation); // Log playing animation
    actions[currentAnimation].reset().fadeIn(0.5).play(); // Reset, fade in, and play animation
    return () => { // Cleanup function
      console.log("🎬 Stopping animation:", currentAnimation); // Log stopping animation
      actions[currentAnimation]?.fadeOut(0.5); // Fade out animation
    };
  }, [animation, actions, animations]); // Run effect when animation, actions, or animations change

  // Handle message playback
  useEffect(() => {
    if (!currentMessage || !currentMessage.audio) return; // Return if no message or audio

    // Play the animation from the message or default to an appropriate idle animation
    let selectedAnim = "Idle"; // Default to idle animation
    
    if (currentMessage.animation && currentMessage.animation !== "") { // Check if message has specific animation
      selectedAnim = currentMessage.animation; // Use message animation
    } else if (animations && animations.length > 0) { // Check if animations exist
      // Look for talking animations first, then fall back to any animation with "talk" in the name
      const talkingAnimation = animations.find((a) => a.name.toLowerCase().includes("talk"))?.name; // Find talking animation
      const firstAnimation = animations[0].name; // Get first animation
      
      selectedAnim = talkingAnimation || firstAnimation; // Select appropriate animation
    }
    
    console.log("Setting animation from message:", selectedAnim); // Log selected animation
    setAnimation(selectedAnim); // Set animation

    setFacialExpression(currentMessage.facialExpression || ""); // Set facial expression
    setLipsync(currentMessage.lipsync || { mouthCues: [] }); // Set lip sync data

    // Handle both base64 string and file path for audio
    const audioSrc = currentMessage.audio.startsWith('data:') ? 
      currentMessage.audio : // Use base64 data directly
      "data:audio/mp3;base64," + currentMessage.audio; // Prepend base64 header
    const audio = new Audio(audioSrc); // Create new audio element
    audio.addEventListener('canplay', () => { // Add event listener for when audio can play
      // Audio is ready to play
      audio.play().catch(e => console.error("Audio play error:", e)); // Play audio and catch errors
    });
    setAudio(audio); // Set audio state

    // Add event listener for when audio ends
    audio.addEventListener('ended', () => {
      // When audio ends, set animation back to an appropriate idle animation
      let idleAnim = "Idle"; // Default to idle animation
      if (animations && animations.length > 0) { // Check if animations exist
        // Look for sitting animations first, then fall back to any idle animation, then to the first available
        const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name; // Find sitting animation
        const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name; // Find idle animation
        const firstAnimation = animations[0].name; // Get first animation
        
        idleAnim = sittingAnimation || idleAnimation || firstAnimation; // Select appropriate idle animation
      }
      console.log("Audio ended, setting animation back to:", idleAnim); // Log idle animation
      setAnimation(idleAnim); // Set idle animation
      setFacialExpression(""); // Reset facial expression
      onMessagePlayed(); // Call callback when message is finished
    });
    
    // Clean up audio on unmount
    return () => {
      if (audio) { // Check if audio exists
        audio.pause(); // Pause audio
        audio.removeAttribute('src'); // Remove source attribute
        audio.load(); // Reset audio
      }
    };
  }, [currentMessage, animations]); // Run effect when currentMessage or animations change

  // Function to smoothly transition morph target values
  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => { // Traverse all children in the scene
      if (child.isSkinnedMesh && child.morphTargetDictionary) { // Check if child is a skinned mesh with morph targets
        const index = child.morphTargetDictionary[target]; // Get morph target index
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) { // Check if target exists
          return; // Return if target doesn't exist
        }
        // Linear interpolation to smoothly transition to target value
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index], // Current value
          value, // Target value
          speed // Interpolation speed
        );

        if (!setupMode) { // Check if not in setup mode
          try {
            set({ // Update Leva control
              [target]: value, // Set target value
            });
          } catch (e) {} // Ignore errors
        }
      }
    });
  };

  const [blink, setBlink] = useState(false); // State for eye blinking
  const [winkLeft, setWinkLeft] = useState(false); // State for left eye wink
  const [winkRight, setWinkRight] = useState(false); // State for right eye wink

  // Frame update function for real-time animations
  useFrame(() => {
    !setupMode && // Only run if not in setup mode
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => { // Iterate through morph targets
        const mapping = facialExpressions[facialExpression]; // Get facial expression mapping
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") { // Skip eye blink targets (handled separately)
          return; // Continue to next iteration
        }
        if (mapping && mapping[key]) { // Check if expression has value for this target
          lerpMorphTarget(key, mapping[key], 0.1); // Apply expression value
        } else {
          lerpMorphTarget(key, 0, 0.1); // Reset to neutral
        }
      });

    // Handle eye blinking and winking
    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5); // Left eye blink/wink
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5); // Right eye blink/wink

    // LIPSYNC
    if (setupMode) { // Check if in setup mode
      return; // Skip lip sync in setup mode
    }

    const appliedMorphTargets = []; // Array to track applied morph targets
    if (message && lipsync) { // Check if message and lipsync data exist
      const currentAudioTime = audio.currentTime; // Get current audio time
      for (let i = 0; i < lipsync.mouthCues.length; i++) { // Iterate through mouth cues
        const mouthCue = lipsync.mouthCues[i]; // Get current mouth cue
        if (
          currentAudioTime >= mouthCue.start && // Check if current time is within cue
          currentAudioTime <= mouthCue.end
        ) {
          appliedMorphTargets.push(corresponding[mouthCue.value]); // Add to applied targets
          lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2); // Apply viseme
          break; // Exit loop after finding matching cue
        }
      }
    }

    // Reset morph targets that weren't applied
    Object.values(corresponding).forEach((value) => { // Iterate through all visemes
      if (appliedMorphTargets.includes(value)) { // Check if viseme was applied
        return; // Skip if applied
      }
      lerpMorphTarget(value, 0, 0.1); // Reset to neutral
    });
  });

  // Leva GUI controls for facial expressions
  useControls("FacialExpressions", {
    chat: button(() => chat()), // Button to trigger chat
    winkLeft: button(() => { // Button to trigger left wink
      setWinkLeft(true); // Set left wink state
      setTimeout(() => setWinkLeft(false), 300); // Reset after 300ms
    }),
    winkRight: button(() => { // Button to trigger right wink
      setWinkRight(true); // Set right wink state
      setTimeout(() => setWinkRight(false), 300); // Reset after 300ms
    }),
    animation: { // Dropdown for animation selection
      value: animation, // Current animation value
      options: animations.map((a) => a.name), // Available animation options
      onChange: (value) => { // Update function
        // If the user selects an empty value, find an appropriate default
        if (!value || value === "") { // Check if value is empty
          let defaultAnimation = "Idle"; // Default to idle animation
          if (animations && animations.length > 0) { // Check if animations exist
            // Look for sitting animations first, then fall back to any idle animation, then to the first available
            const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name; // Find sitting animation
            const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name; // Find idle animation
            const firstAnimation = animations[0].name; // Get first animation
            
            defaultAnimation = sittingAnimation || idleAnimation || firstAnimation; // Select appropriate default
          }
          console.log("Animation control set to default:", defaultAnimation); // Log default animation
          setAnimation(defaultAnimation); // Set default animation
        } else {
          console.log("Animation control changed to:", value); // Log new animation
          setAnimation(value); // Set new animation
        }
      },
    },
    facialExpression: { // Dropdown for facial expression selection
      options: Object.keys(facialExpressions), // Available expression options
      onChange: (value) => setFacialExpression(value), // Update expression on change
    },
    enableSetupMode: button(() => { // Button to enable setup mode
      setupMode = true; // Set setup mode flag
    }),
    disableSetupMode: button(() => { // Button to disable setup mode
      setupMode = false; // Clear setup mode flag
    }),
    logMorphTargetValues: button(() => { // Button to log current morph target values
      const emotionValues = {}; // Object to store emotion values
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => { // Iterate through morph targets
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") { // Skip eye blink targets
          return; // Continue to next iteration
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[ // Get current morph target influence
            nodes.EyeLeft.morphTargetDictionary[key] // Get target index
          ];
        if (value > 0.01) { // Check if value is significant
          emotionValues[key] = value; // Add to emotion values
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2)); // Log emotion values
    }),
  });

  // Leva GUI controls for morph targets
  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => { // Map morph targets to controls
        return {
          [key]: { // Create control for each morph target
            label: key, // Label for control
            value: 0, // Initial value
            min: nodes.EyeLeft.morphTargetInfluences[ // Minimum value
              nodes.EyeLeft.morphTargetDictionary[key] // Get target index
            ],
            max: 1, // Maximum value
            onChange: (val) => { // Update function
              if (setupMode) { // Check if in setup mode
                lerpMorphTarget(key, val, 1); // Apply morph target value directly
              }
            },
          },
        };
      })
    )
  );

  // Effect for automatic eye blinking
  useEffect(() => {
    let blinkTimeout; // Variable to store timeout ID
    const nextBlink = () => { // Function to schedule next blink
      blinkTimeout = setTimeout(() => { // Set timeout for next blink
        setBlink(true); // Trigger blink
        setTimeout(() => { // Set timeout to end blink
          setBlink(false); // End blink
          nextBlink(); // Schedule next blink
        }, 200); // Blink duration: 200ms
      }, THREE.MathUtils.randInt(1000, 5000)); // Random interval: 1-5 seconds
    };
    nextBlink(); // Start blinking
    return () => clearTimeout(blinkTimeout); // Clear timeout on unmount
  }, []);

  // Ensure animation always defaults to an appropriate idle animation when empty or invalid
  useEffect(() => {
    console.log("Animation state changed to:", animation); // Log animation change
    if (!animation || animation === "") { // Check if animation is empty
      // Find an appropriate default animation
      let defaultAnimation = "Idle"; // Default to idle animation
      if (animations && animations.length > 0) { // Check if animations exist
        // Look for sitting animations first, then fall back to any idle animation, then to the first available
        const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name; // Find sitting animation
        const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name; // Find idle animation
        const firstAnimation = animations[0].name; // Get first animation
        
        defaultAnimation = sittingAnimation || idleAnimation || firstAnimation; // Select appropriate default
      }
      console.log("Setting animation to default:", defaultAnimation); // Log default animation
      setAnimation(defaultAnimation); // Set default animation
    }
  }, [animation, animations]); // Run effect when animation or animations change

  // Main render function for the student avatar
  return (
    <group {...props} dispose={null} ref={group}> {/* Avatar group container */}
      {/* Listening indicator above the avatar */}
      {isListening && ( // Show only when listening
        <Text position={[0, 2.5, 0]} fontSize={0.2} color="#4ade80"> {/* Position and style text */}
          👂 Listening... {/* Display listening indicator */}
        </Text>
      )}

      <primitive object={nodes.Hips} /> {/* Hips bone as primitive */}
      {/* Render all skinned meshes with their morph targets */}
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Hair"
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

// Preload GLTF models for better performance
useGLTF.preload("/models/64f1a714fe61576b46f27ca2.glb");
useGLTF.preload("/models/untitled.glb");