/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState, useMemo } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

// Store bone references for gesture animation
let gestureBones = {};

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF("/models/67a47721736ce9f3e126d847.glb");
  const { message, onMessagePlayed } = useChat();

  const group = useRef();
  const { animations } = useGLTF("/models/animations.glb");
  const { actions } = useAnimations(animations, group);

  const [animation, setAnimation] = useState("Idle");
  const [secondaryAnimation, setSecondaryAnimation] = useState(null);
  const [lipsync, setLipsync] = useState();
  const [currentMessage, setCurrentMessage] = useState(null);
  const [audio, setAudio] = useState(null);
  const [facialExpression, setFacialExpression] = useState("");
  const [gestureData, setGestureData] = useState({ compressed: { bones: [], frames: [] } });
  
  // Animation timing
  const lastUpdateRef = useRef(0);
  const currentFrameRef = useRef(0);

  // Log all bone names for debugging
  useEffect(() => {
    console.log("Available bones in GLB model:");
    scene.traverse((child) => {
      if (child.isBone) {
        console.log("- Bone:", child.name);
        gestureBones[child.name] = child;
      }
    });
  }, [scene]);

  const talkingAnimations = ["Talking_0", "Talking_1", "Talking_2", "Talking_1", "Talking_4", "Talking_5", "Talking_6", "Talking_7"];
  const availableAnimations = animations.map((a) => a.name);

  useEffect(() => {
    if (message) {
      setCurrentMessage(message);
      if (message.gesture) {
        setGestureData(message.gesture);
        console.log("Gesture data received:", message.gesture);
        currentFrameRef.current = 0;
      }
    }
  }, [message]);

  useEffect(() => {
    if (!currentMessage || !currentMessage.audio) return;

    // Pilih animasi dari AI, fallback ke random talking animation
    let selectedAnim = "Idle";
    if (currentMessage.animation && availableAnimations.includes(currentMessage.animation)) {
      selectedAnim = currentMessage.animation;
    } else if ((currentMessage.animation || currentMessage.text) && talkingAnimations.length > 0) {
      // If there's text but no specific animation, randomly select a talking animation
      const randomIndex = Math.floor(Math.random() * talkingAnimations.length);
      selectedAnim = talkingAnimations[randomIndex];
    }
    setAnimation(selectedAnim);
    
    // Set secondary animation if provided
    setSecondaryAnimation(currentMessage.secondaryAnimation || null);
    
    console.log(`📥 Received animation data: Primary=${currentMessage.animation}, Secondary=${currentMessage.secondaryAnimation}`);
    console.log(`🔄 Setting animations: Primary=${selectedAnim}, Secondary=${currentMessage.secondaryAnimation || null}`);

    setFacialExpression(currentMessage.facialExpression || "smile");
    setLipsync(currentMessage.lipsync || { mouthCues: [] });

    // Handle both base64 string and file path
    const audioSrc = currentMessage.audio.startsWith('data:') ? 
      currentMessage.audio : 
      "data:audio/mp3;base64," + currentMessage.audio;
    const audio = new Audio(audioSrc);
    audio.addEventListener('canplay', () => {
      // Audio is ready to play
      audio.play().catch(e => console.error("Audio play error:", e));
    });
    setAudio(audio);

    audio.addEventListener('ended', () => {
      setAnimation("Idle");
      setSecondaryAnimation(null);
      setFacialExpression("neutral");
      onMessagePlayed();
    });
  
    // Clean up audio on unmount
    return () => {
      if (audio) {
        audio.pause();
        audio.removeAttribute('src');
        audio.load();
      }
    };
  }, [currentMessage]);

  useEffect(() => {
    // Handle primary animation
    if (animation && actions[animation]) {
      console.log("🎬 Playing primary animation:", animation);
      actions[animation].reset().fadeIn(0.2).play();
    } else if (animation) {
      console.warn("⚠️ Primary animation not found:", animation);
    }
    
    // Handle secondary animation
    if (secondaryAnimation && actions[secondaryAnimation]) {
      console.log("🎬 Playing secondary animation:", secondaryAnimation);
      actions[secondaryAnimation].reset().fadeIn(0.2).play();
    } else if (secondaryAnimation) {
      console.warn("⚠️ Secondary animation not found:", secondaryAnimation);
    }
    
    // Log current animation states
    console.log(`🔄 Current animation states: Primary=${animation}, Secondary=${secondaryAnimation}`);
    
    // Cleanup function
    return () => {
      if (animation && actions[animation]) {
        console.log("🛑 Stopping primary animation:", animation);
        actions[animation]?.fadeOut(0.2);
      }
      if (secondaryAnimation && actions[secondaryAnimation]) {
        console.log("🛑 Stopping secondary animation:", secondaryAnimation);
        actions[secondaryAnimation]?.fadeOut(0.2);
      }
    };
  }, [animation, secondaryAnimation, actions]);

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (index === undefined || child.morphTargetInfluences[index] === undefined) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {}
        }
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  // const [facialExpression, setFacialExpression] = useState("");
  // const [audio, setAudio] = useState();

  useFrame((state, delta) => {
    // Handle gesture animations
    if (gestureData && gestureData.compressed && gestureData.compressed.frames.length > 0) {
      const { bones, frames } = gestureData.compressed;
      
      // Update timing
      const now = performance.now() / 1000; // Convert to seconds
      if (lastUpdateRef.current === 0) {
        lastUpdateRef.current = now;
      }
      
      const elapsedTime = now - lastUpdateRef.current;
      lastUpdateRef.current = now;
      
      // Find current and next frames for interpolation
      let currentFrame = frames[currentFrameRef.current];
      let nextFrame = frames[Math.min(currentFrameRef.current + 1, frames.length - 1)];
      
      // Advance frame based on elapsed time (assuming 30 FPS source)
      const frameDuration = 1 / 30;
      if (elapsedTime >= frameDuration) {
        currentFrameRef.current = Math.min(currentFrameRef.current + 1, frames.length - 1);
        currentFrame = frames[currentFrameRef.current];
        nextFrame = frames[Math.min(currentFrameRef.current + 1, frames.length - 1)];
      }
      
      // Apply bone rotations
      if (currentFrame && currentFrame.rot) {
        const t = Math.min(1, (elapsedTime % frameDuration) / frameDuration); // Interpolation factor
        
        for (let i = 0; i < bones.length; i++) {
          const boneName = bones[i];
          const bone = gestureBones[boneName];
          
          if (bone && currentFrame.rot[i]) {
            // Get current and next quaternions
            const currentQuat = new THREE.Quaternion(
              currentFrame.rot[i][0],
              currentFrame.rot[i][1],
              currentFrame.rot[i][2],
              currentFrame.rot[i][3]
            );
            
            let finalQuat = currentQuat;
            
            // If we have a next frame, interpolate between them
            if (nextFrame && nextFrame.rot && nextFrame.rot[i]) {
              const nextQuat = new THREE.Quaternion(
                nextFrame.rot[i][0],
                nextFrame.rot[i][1],
                nextFrame.rot[i][2],
                nextFrame.rot[i][3]
              );
              
              // Spherical linear interpolation
              finalQuat = currentQuat.clone().slerp(nextQuat, t);
            }
            
            // Apply rotation to bone
            bone.quaternion.copy(finalQuat);
          }
        }
      }
    }
    
    // Handle facial expressions and lipsync
    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    // LIPSYNC
    if (setupMode) {
      return;
    }
    const appliedMorphTargets = [];
    // Check if all required objects exist and audio is ready
    if (currentMessage && lipsync && audio && audio.readyState >= 2) {
      // Check if lipsync and lipsync.mouthCues exist and are arrays
      const mouthCues = lipsync.mouthCues || [];
      if (Array.isArray(mouthCues)) {
        const currentAudioTime = audio.currentTime || 0;
        for (let i = 0; i < mouthCues.length; i++) {
          const mouthCue = mouthCues[i];
          if (mouthCue && 
              typeof mouthCue.start === 'number' && 
              typeof mouthCue.end === 'number' &&
              currentAudioTime >= mouthCue.start &&
              currentAudioTime <= mouthCue.end) {
            if (corresponding[mouthCue.value]) {
              appliedMorphTargets.push(corresponding[mouthCue.value]);
              lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2);
            }
            break;
          }
        }
      }
    }

    Object.values(corresponding).forEach((value) => {
      if (appliedMorphTargets.includes(value)) {
        return;
      }
      lerpMorphTarget(value, 0, 0.1);
    });
  });

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Headwear.geometry}
        material={materials.Wolf3D_Headwear}
        skeleton={nodes.Wolf3D_Headwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/models/67a47721736ce9f3e126d847.glb");
useGLTF.preload("/models/untitled.glb");