/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";
import { Text } from "@react-three/drei";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

export function AvatarStudent(props) {
  const { nodes, materials, scene } = useGLTF(
    "/models/64f1a714fe61576b46f27ca2.glb"
  );

  const { message, onMessagePlayed, chat } = useChat();

  const [lipsync, setLipsync] = useState();

  const { animations } = useGLTF("/models/animations.glb");

  const group = useRef();
  const { actions, mixer } = useAnimations(animations, group);
  const [animation, setAnimation] = useState("");
  const [currentMessage, setCurrentMessage] = useState(null);
  const [audio, setAudio] = useState(null);
  const [facialExpression, setFacialExpression] = useState("");
  const [userInput, setUserInput] = useState(""); // New state for user input
  const [isListening, setIsListening] = useState(false); // New state for listening indicator

  // Set the initial animation based on available animations
  useEffect(() => {
    if (animations && animations.length > 0) {
      console.log("Available animations:", animations.map(a => a.name));
      // Look for sitting animations first, then fall back to any idle animation, then to the first available
      const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name;
      const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name;
      const firstAnimation = animations[0].name;
      
      const initialAnimation = sittingAnimation || idleAnimation || firstAnimation;
      setAnimation(initialAnimation);
      console.log("Setting initial animation to:", initialAnimation);
    }
  }, [animations]);

  // Handle user input to show listening expression
  useEffect(() => {
    if (message && message.text) {
      // Set listening state and facial expression when user sends input
      setIsListening(true);
      setFacialExpression("smile");
      setUserInput(message.text);
      
      // Reset to default expression after a delay
      const timer = setTimeout(() => {
        setIsListening(false);
        setFacialExpression("default");
        setUserInput("");
      }, 3000);
      
      return () => clearTimeout(timer);
    }
  }, [message]);

  // Play animations
  useEffect(() => {
    // Always ensure we have a valid animation
    const currentAnimation = (animation && animation !== "") ? animation : "Idle";
    console.log("Trying to play animation:", currentAnimation);
    
    // Check if animation exists
    if (!actions[currentAnimation] || !animations) {
      console.log("Animation not found or no animations loaded");
      // Try to find an appropriate fallback animation
      if (animations && animations.length > 0) {
        // Look for sitting animations first, then fall back to any idle animation, then to the first available
        const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name;
        const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name;
        const firstAnimation = animations[0].name;
        
        const fallbackAnimation = sittingAnimation || idleAnimation || firstAnimation;
        
        if (fallbackAnimation && actions[fallbackAnimation]) {
          console.log("Falling back to animation:", fallbackAnimation);
          setAnimation(fallbackAnimation);
          return;
        }
      }
      return;
    }

    console.log("🎬 Playing animation:", currentAnimation);
    actions[currentAnimation].reset().fadeIn(0.5).play();
    return () => {
      console.log("🎬 Stopping animation:", currentAnimation);
      actions[currentAnimation]?.fadeOut(0.5);
    };
  }, [animation, actions, animations]);

  // Handle message playback
  useEffect(() => {
    if (!currentMessage || !currentMessage.audio) return;

    // Play the animation from the message or default to an appropriate idle animation
    let selectedAnim = "Idle"; // fallback
    
    if (currentMessage.animation && currentMessage.animation !== "") {
      selectedAnim = currentMessage.animation;
    } else if (animations && animations.length > 0) {
      // Look for talking animations first, then fall back to any animation with "talk" in the name
      const talkingAnimation = animations.find((a) => a.name.toLowerCase().includes("talk"))?.name;
      const firstAnimation = animations[0].name;
      
      selectedAnim = talkingAnimation || firstAnimation;
    }
    
    console.log("Setting animation from message:", selectedAnim);
    setAnimation(selectedAnim);

    setFacialExpression(currentMessage.facialExpression || "");
    setLipsync(currentMessage.lipsync || { mouthCues: [] });

    // Handle both base64 string and file path
    const audioSrc = currentMessage.audio.startsWith('data:') ? 
      currentMessage.audio : 
      "data:audio/mp3;base64," + currentMessage.audio;
    const audio = new Audio(audioSrc);
    audio.addEventListener('canplay', () => {
      // Audio is ready to play
      audio.play().catch(e => console.error("Audio play error:", e));
    });
    setAudio(audio);

    audio.addEventListener('ended', () => {
      // When audio ends, set animation back to an appropriate idle animation
      let idleAnim = "Idle"; // fallback
      if (animations && animations.length > 0) {
        // Look for sitting animations first, then fall back to any idle animation, then to the first available
        const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name;
        const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name;
        const firstAnimation = animations[0].name;
        
        idleAnim = sittingAnimation || idleAnimation || firstAnimation;
      }
      console.log("Audio ended, setting animation back to:", idleAnim);
      setAnimation(idleAnim);
      setFacialExpression("");
      onMessagePlayed();
    });
    
    // Clean up audio on unmount
    return () => {
      if (audio) {
        audio.pause();
        audio.removeAttribute('src');
        audio.load();
      }
    };
  }, [currentMessage, animations]);

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {}
        }
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);

  useFrame(() => {
    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    // LIPSYNC
    if (setupMode) {
      return;
    }

    const appliedMorphTargets = [];
    if (message && lipsync) {
      const currentAudioTime = audio.currentTime;
      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        if (
          currentAudioTime >= mouthCue.start &&
          currentAudioTime <= mouthCue.end
        ) {
          appliedMorphTargets.push(corresponding[mouthCue.value]);
          lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2);
          break;
        }
      }
    }

    Object.values(corresponding).forEach((value) => {
      if (appliedMorphTargets.includes(value)) {
        return;
      }
      lerpMorphTarget(value, 0, 0.1);
    });
  });

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => {
        // If the user selects an empty value, find an appropriate default
        if (!value || value === "") {
          let defaultAnimation = "Idle"; // fallback
          if (animations && animations.length > 0) {
            // Look for sitting animations first, then fall back to any idle animation, then to the first available
            const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name;
            const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name;
            const firstAnimation = animations[0].name;
            
            defaultAnimation = sittingAnimation || idleAnimation || firstAnimation;
          }
          console.log("Animation control set to default:", defaultAnimation);
          setAnimation(defaultAnimation);
        } else {
          console.log("Animation control changed to:", value);
          setAnimation(value);
        }
      },
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  // Ensure animation always defaults to an appropriate idle animation when empty or invalid
  useEffect(() => {
    console.log("Animation state changed to:", animation);
    if (!animation || animation === "") {
      // Find an appropriate default animation
      let defaultAnimation = "Idle"; // fallback
      if (animations && animations.length > 0) {
        // Look for sitting animations first, then fall back to any idle animation, then to the first available
        const sittingAnimation = animations.find((a) => a.name.toLowerCase().includes("sit"))?.name;
        const idleAnimation = animations.find((a) => a.name.toLowerCase().includes("idle"))?.name;
        const firstAnimation = animations[0].name;
        
        defaultAnimation = sittingAnimation || idleAnimation || firstAnimation;
      }
      console.log("Setting animation to default:", defaultAnimation);
      setAnimation(defaultAnimation);
    }
  }, [animation, animations]);

  return (
    <group {...props} dispose={null} ref={group}>
      {/* Listening indicator above the avatar */}
{isListening && (
  <Text position={[0, 2.5, 0]} fontSize={0.2} color="#4ade80">
    👂 Listening...
  </Text>
)}

      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Hair"
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/64f1a714fe61576b46f27ca2.glb");
useGLTF.preload("/models/animations.glb");
