import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const annotationDir = path.join(__dirname, "..", "annotations");
const csvPath = path.join(annotationDir, "gesture_annotations.csv");
const jsonlPath = path.join(annotationDir, "gesture_logs.jsonl");
const HEADER = ["annotation_id","session_id","timestamp","user_input","ai_response","predicted_gesture","predicted_gesture_sequence","confidence","audio_duration","animation_clip","lip_sync_file","pedagogical_context","gold_gesture_label","gold_gesture_sequence","gesture_function","suitability_score","naturalness_score","sync_score","engagement_support_score","annotator_name","validation_status","notes"];
function ensureFiles(){ if(!fs.existsSync(annotationDir)) fs.mkdirSync(annotationDir,{recursive:true}); if(!fs.existsSync(csvPath)) fs.writeFileSync(csvPath, HEADER.join(",")+"\n", "utf8"); if(!fs.existsSync(jsonlPath)) fs.writeFileSync(jsonlPath,"","utf8"); }
function csvCell(value){ if(value===undefined||value===null) return ""; const text=Array.isArray(value)?value.join("|"):String(value); return `"${text.replace(/"/g,'""')}"`; }
function genId(){ return `ANN-${Date.now()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`; }
function seq(value){ if(!value) return ""; if(Array.isArray(value)) return value.join("|"); return String(value); }
export function normalizeAnnotation(data={}){ const predicted = data.predicted_gesture || data.gesture || data.gestureLabel || (Array.isArray(data.gestureLabels)?data.gestureLabels[0]:"") || "normal"; return { annotation_id: data.annotation_id || genId(), session_id: data.session_id || data.sessionId || "", timestamp: data.timestamp || new Date().toISOString(), user_input: data.user_input || data.userMessage || data.message || data.question || "", ai_response: data.ai_response || data.text || data.response || data.answer || "", predicted_gesture: predicted, predicted_gesture_sequence: seq(data.predicted_gesture_sequence || data.gestureLabels || data.gestures || [predicted]), confidence: data.confidence ?? data.gestureConfidence ?? data.gesturePrediction?.confidence ?? "", audio_duration: data.audio_duration ?? data.audioDuration ?? data.duration ?? "", animation_clip: data.animation_clip || data.animationClip || predicted, lip_sync_file: data.lip_sync_file || data.lipsync || data.lipSyncFile || "", pedagogical_context: data.pedagogical_context || "", gold_gesture_label: data.gold_gesture_label || "", gold_gesture_sequence: seq(data.gold_gesture_sequence || ""), gesture_function: data.gesture_function || "", suitability_score: data.suitability_score || "", naturalness_score: data.naturalness_score || "", sync_score: data.sync_score || "", engagement_support_score: data.engagement_support_score || "", annotator_name: data.annotator_name || "", validation_status: data.validation_status || "system-log", notes: data.notes || "" }; }
export function saveGestureAnnotation(data){ ensureFiles(); const row=normalizeAnnotation(data); fs.appendFileSync(jsonlPath, JSON.stringify(row)+"\n", "utf8"); fs.appendFileSync(csvPath, HEADER.map((h)=>csvCell(row[h])).join(",")+"\n", "utf8"); return row; }
export function listGestureAnnotations(limit=100){ ensureFiles(); const rows=fs.readFileSync(jsonlPath,"utf8").split("\n").filter(Boolean); return rows.slice(-limit).map(line=>{try{return JSON.parse(line)}catch{return null}}).filter(Boolean); }
export function getGestureAnnotationCSVPath(){ ensureFiles(); return csvPath; }
