import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const exportDir = path.join(__dirname, "..", "exports");
const csvPath = path.join(exportDir, "gesture_mapping_timeline.csv");
const jsonPath = path.join(exportDir, "gesture_mapping_timeline.json");
const HEADER=["mapping_id","session_id","timestamp","audio_file","audio_duration","segment_index","start_time","end_time","duration","gesture_label","animation_clip","gesture_function","pedagogical_context","mouth_cue_count","dominant_mouth_cue","annotation_status","gold_gesture_label","suitability_score","naturalness_score","sync_score","engagement_support_score","annotator_name","notes"];
function ensure(){ if(!fs.existsSync(exportDir)) fs.mkdirSync(exportDir,{recursive:true}); if(!fs.existsSync(csvPath)) fs.writeFileSync(csvPath, HEADER.join(",")+"\n", "utf8"); if(!fs.existsSync(jsonPath)) fs.writeFileSync(jsonPath,"[]","utf8"); }
function csvCell(value){ if(value===undefined||value===null) return ""; const text=Array.isArray(value)?value.join("|"):String(value); return `"${text.replace(/"/g,'""')}"`; }
function genId(){ return `MAP-${Date.now()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`; }
function norm(segment,index,meta={}){ const start=Number(segment.start_time ?? segment.start ?? 0); const end=Number(segment.end_time ?? segment.end ?? 0); return { mapping_id: segment.mapping_id || meta.mapping_id || genId(), session_id: segment.session_id || meta.session_id || "", timestamp: segment.timestamp || meta.timestamp || new Date().toISOString(), audio_file: segment.audio_file || meta.audio_file || "", audio_duration: segment.audio_duration ?? meta.audio_duration ?? "", segment_index: segment.segment_index ?? index, start_time:start, end_time:end, duration: segment.duration ?? Math.max(0,end-start).toFixed(3), gesture_label: segment.gesture_label || segment.gesture || segment.label || "normal", animation_clip: segment.animation_clip || segment.animationClip || segment.gesture_label || segment.gesture || "normal", gesture_function: segment.gesture_function || "", pedagogical_context: segment.pedagogical_context || "", mouth_cue_count: segment.mouth_cue_count ?? "", dominant_mouth_cue: segment.dominant_mouth_cue || "", annotation_status: segment.annotation_status || "mapped", gold_gesture_label: segment.gold_gesture_label || "", suitability_score: segment.suitability_score || "", naturalness_score: segment.naturalness_score || "", sync_score: segment.sync_score || "", engagement_support_score: segment.engagement_support_score || "", annotator_name: segment.annotator_name || "", notes: segment.notes || "" }; }
export function appendMappingSegments(segments=[], meta={}){ ensure(); if(!Array.isArray(segments)) throw new Error("segments harus berupa array"); const normalized=segments.map((s,i)=>norm(s,i,meta)); const rows=normalized.map((r)=>HEADER.map((k)=>csvCell(r[k])).join(",")); if(rows.length) fs.appendFileSync(csvPath, rows.join("\n")+"\n", "utf8"); let old=[]; try{ old=JSON.parse(fs.readFileSync(jsonPath,"utf8")); }catch{} fs.writeFileSync(jsonPath, JSON.stringify([...old,...normalized],null,2), "utf8"); return { csvPath,jsonPath,count:normalized.length,data:normalized}; }
export function overwriteMappingSegments(segments=[], meta={}){ if(!fs.existsSync(exportDir)) fs.mkdirSync(exportDir,{recursive:true}); fs.writeFileSync(csvPath, HEADER.join(",")+"\n", "utf8"); fs.writeFileSync(jsonPath,"[]","utf8"); return appendMappingSegments(segments,meta); }
export function getMappingCsvPath(){ ensure(); return csvPath; }
export function getMappingJsonPath(){ ensure(); return jsonPath; }
