import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const exportDir = path.join(__dirname, "..", "exports");
const csvPath = path.join(exportDir, "sentence_gesture_mapping.csv");
const jsonPath = path.join(exportDir, "sentence_gesture_mapping.json");
const HEADER = ["session_id","timestamp","sentence_index","sentence_text","audio_file","audio_duration","start_time","end_time","duration","gesture_label","animation_clip","gesture_source","gesture_function","pedagogical_context","mouth_cue_count","dominant_mouth_cue","annotation_status","gold_gesture_label","suitability_score","naturalness_score","sync_score","engagement_support_score","annotator_name","notes"];
function ensureFiles(){ if(!fs.existsSync(exportDir)) fs.mkdirSync(exportDir,{recursive:true}); if(!fs.existsSync(csvPath)) fs.writeFileSync(csvPath, HEADER.join(",")+"\n", "utf8"); if(!fs.existsSync(jsonPath)) fs.writeFileSync(jsonPath,"[]","utf8"); }
function csvCell(value){ if(value===undefined||value===null) return ""; const text=Array.isArray(value)?value.join("|"):String(value); return `"${text.replace(/"/g,'""')}"`; }
function normalize(row={}, index=0, meta={}){ return { session_id: row.session_id || meta.session_id || "", timestamp: row.timestamp || meta.timestamp || new Date().toISOString(), sentence_index: row.sentence_index ?? index, sentence_text: row.sentence_text || "", audio_file: row.audio_file || meta.audio_file || "", audio_duration: row.audio_duration ?? meta.audio_duration ?? "", start_time: row.start_time ?? "", end_time: row.end_time ?? "", duration: row.duration ?? "", gesture_label: row.gesture_label || "normal", animation_clip: row.animation_clip || row.gesture_label || "normal", gesture_source: row.gesture_source || "", gesture_function: row.gesture_function || "", pedagogical_context: row.pedagogical_context || "", mouth_cue_count: row.mouth_cue_count ?? "", dominant_mouth_cue: row.dominant_mouth_cue || "", annotation_status: row.annotation_status || "mapped", gold_gesture_label: row.gold_gesture_label || "", suitability_score: row.suitability_score || "", naturalness_score: row.naturalness_score || "", sync_score: row.sync_score || "", engagement_support_score: row.engagement_support_score || "", annotator_name: row.annotator_name || "", notes: row.notes || "" }; }
export function saveSentenceGestureMapping(rows=[], meta={}, mode="append"){ ensureFiles(); if(!Array.isArray(rows)) throw new Error("rows harus berupa array"); const normalized=rows.map((row,index)=>normalize(row,index,meta)); if(mode==="overwrite"){ fs.writeFileSync(csvPath, HEADER.join(",")+"\n", "utf8"); fs.writeFileSync(jsonPath,"[]","utf8"); } const csvRows=normalized.map((row)=>HEADER.map((key)=>csvCell(row[key])).join(",")); if(csvRows.length) fs.appendFileSync(csvPath,csvRows.join("\n")+"\n","utf8"); let oldJson=[]; try{ oldJson=JSON.parse(fs.readFileSync(jsonPath,"utf8")); }catch{} fs.writeFileSync(jsonPath, JSON.stringify([...oldJson,...normalized],null,2), "utf8"); return { success:true, count: normalized.length, csvPath, jsonPath, data: normalized }; }
export function getCsvPath(){ ensureFiles(); return csvPath; }
export function getJsonPath(){ ensureFiles(); return jsonPath; }
